version: "3.9"

services:
  app:
    build: .
    container_name: fastapi-escola
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]